<template><div><h1 id="announcing-mixin-flutter-desktop-open-source" tabindex="-1"><a class="header-anchor" href="#announcing-mixin-flutter-desktop-open-source" aria-hidden="true">#</a> Announcing Mixin Flutter Desktop Open Source</h1>
<p>We are announcing a new Mixin Messenger desktop version open source, we use Flutter to build a new cross-platform version app. GitHub: <a href="https://github.com/MixinNetwork/flutter-app" target="_blank" rel="noopener noreferrer">https://github.com/MixinNetwork/flutter-app<ExternalLinkIcon/></a></p>
<p><img src="@source/blog/2022/announcing-mixin-flutter-desktop-open-source/mixin-desktop.png" alt="mixin-desktop"></p>
<h2 id="flutter" tabindex="-1"><a class="header-anchor" href="#flutter" aria-hidden="true">#</a> Flutter</h2>
<p>When we plan to develop a desktop app for Windows, Linux and macOS, we choose Electron before, but as you know the Electron app is too big and costs much memory. So we looking for other cross-platform solutions, Flutter is an open source framework for building multi-platform applications. Our team paid attention to flutter very early. When it’s support desktop, we think it’s time to try Flutter to build our new Mixin Messenger desktop app.</p>
<p>Mixin Messenger is an open source end-to-end encryption messenger that uses signal protocol focused on safety and private message. For this purpose, We implement Signal Protocol on dart <a href="https://github.com/MixinNetwork/libsignal_protocol_dart" target="_blank" rel="noopener noreferrer">https://github.com/MixinNetwork/libsignal_protocol_dart<ExternalLinkIcon/></a>. And some plugins like drag files, paste images and files, open WebView on desktop. You can find the plugins on <a href="https://github.com/MixinNetwork/flutter-plugins" target="_blank" rel="noopener noreferrer">https://github.com/MixinNetwork/flutter-plugins<ExternalLinkIcon/></a> or <a href="https://pub.dev/publishers/mixin.dev/packages" target="_blank" rel="noopener noreferrer">https://pub.dev/publishers/mixin.dev/packages<ExternalLinkIcon/></a></p>
<p><img src="@source/blog/2022/announcing-mixin-flutter-desktop-open-source/plugins.png" alt="plugins"></p>
<h2 id="summary" tabindex="-1"><a class="header-anchor" href="#summary" aria-hidden="true">#</a> Summary</h2>
<p>Thanks for our remote teammates collaborative development of the Mixin Messenger Flutter desktop. Welcome Flutter developers contribute flutter app and issue bugs on GitHub. Hope to meet you on Mixin Messenger.</p>
<p>Official website download <a href="https://mixin.one/mm" target="_blank" rel="noopener noreferrer">https://mixin.one/mm<ExternalLinkIcon/></a>
Windows store download <a href="https://www.microsoft.com/en-us/p/mixin-desktop/9nq6hf99b8nj" target="_blank" rel="noopener noreferrer">https://www.microsoft.com/en-us/p/mixin-desktop/9nq6hf99b8nj<ExternalLinkIcon/></a>
Mac App Store <a href="https://apps.apple.com/us/app/mixin-messenger/id1571128582" target="_blank" rel="noopener noreferrer">https://apps.apple.com/us/app/mixin-messenger/id1571128582<ExternalLinkIcon/></a></p>
<h2 id="about-mixin-network" tabindex="-1"><a class="header-anchor" href="#about-mixin-network" aria-hidden="true">#</a> About Mixin Network</h2>
<p>Mixin Network is an open-source, lightning-fast, and decentralized Web3 platform to bring speed and scalability to the blockchain. Mixin allows blockchains to gain trillions of TPS, sub-second final confirmation, zero transaction fee, enhanced privacy, and unlimited extensibility.</p>
<p>Mixin Network is a PoS network with 26 full nodes. As a layer-2 solution, it has supported 41 public blockchains including Bitcoin, Ethereum, Monero, Polkadot, etc. The total assets on the network have been over 2 billion US Dollars. Mixin is also a full-featured financial platform with functions of AMM, aggregating trade, pending orders on Exchange platforms, unbiased stable currency, etc. Mixin Network is dedicated to providing users with a decentralized blockchain infrastructure that always puts security, privacy, and decentralization first.</p>
<h2 id="follow-us" tabindex="-1"><a class="header-anchor" href="#follow-us" aria-hidden="true">#</a> Follow us:</h2>
<p>Official Website:<a href="https://mixin.one/" target="_blank" rel="noopener noreferrer">https://mixin.one<ExternalLinkIcon/></a></p>
<p>Twitter: <a href="https://twitter.com/Mixin_Network/" target="_blank" rel="noopener noreferrer">https://twitter.com/Mixin_Network<ExternalLinkIcon/></a></p>
<p>Facebook: <a href="https://www.facebook.com/MixinNetwork" target="_blank" rel="noopener noreferrer">https://www.facebook.com/MixinNetwork<ExternalLinkIcon/></a></p>
</div></template>
