<template><div><h1 id="zktube-labs-establishes-strategic-partnership-with-mixin-network" tabindex="-1"><a class="header-anchor" href="#zktube-labs-establishes-strategic-partnership-with-mixin-network" aria-hidden="true">#</a> zkTube Labs Establishes Strategic Partnership With Mixin Network</h1>
<p><img src="@source/blog/2021/zktube-labs-establishes-strategic-partnership-with-mixin-network/zktube-mixin.png" alt="zktube-mixin"></p>
<p>zkTube Labs is pleased to announce a strategic partnership with Mixin Network. Based on the premise that combines zero-knowledge protocol and Layer 2, zkTube is referred to as a Layer 2 protocol that utilizes zero-knowledge proof and ZK rollup for the individual and businesses to realize lower transaction fees plus high throughput transactions between ETH or Ethereum and ERC-20.</p>
<p>It utilizes zero-knowledge proof to offer solutions to the problems and issues of expansion, data availability, privacy for Ethereum, and all data is synchronized and stored on the <a href="https://zktube.io/" target="_blank" rel="noopener noreferrer">zkTube mainnet<ExternalLinkIcon/></a>. zkTube is poised to become the best Layer 2 environment for payments with no more than 0.01 cents per transaction, and TPS up to 3000+. It offers great value for people. Soon, it will be a point for financial institutions to move to Ethereum, to provide a more friendly payment system worldwide.</p>
<p>zkTube’s global community includes 60,000 members from Australia, Arabia, Russia, Vietnam, China, and South Korea.</p>
<p>Mixin Network is a simple UTXO transaction network, focused on transaction functionalities and privacy protection, which is composed of a single theoretically permanent Kernel, many dynamic Domains and different multipurpose Domain Extensions, to formulate an extended star topology. Kernel has a simple logic, it can achieve almost unlimited concurrency performance.</p>
<p>Besides blockchain projects, as a next-generation transaction network, Mixin Network also provides transaction solutions for other non-blockchain projects.</p>
<p>Through the partnership, the two parties will conduct in-depth collaboration in market promotion, network construction, and community expansion across the globe. zkTube will collaborate Mixin with its multi-chain network ecosystem and wallet service.</p>
<p>Users are welcome to join the vibrant communities of zkTube and Mixin Network, meet all the cryptocurrency friends, get the latest news about these two, and get benefits from the secure and scalable blockchain infrastructure.</p>
<h2 id="about-zktube" tabindex="-1"><a class="header-anchor" href="#about-zktube" aria-hidden="true">#</a> About zkTube</h2>
<p>zkTube is a project built and developed on Layer 2 based on the PLONK algorithm protocol using ZK-Rollup technology. It can improve scalability by transferring batches of transactions to a single transaction. Its essence is to compress the user state on the chain and store it in a Merkle tree and transfer the user state change to the chain while ensuring the user state change process’s correctness through a Zero-Knowledge proof mechanism. The cost of directly processing user state changes on the chain is relatively high, but only using the smart contract on the chain to verify the correctness of a zero-knowledge proof is relatively low. In addition, the required remittance information is transmitted to the contract along with the certificate, which is convenient for users to verify accounts.</p>
<p>zkTube aims to become an indispensable Layer 2 environment builder and Layer 2 solution provider in Web3.0. The realization of the asset migration from Layer 1 to Layer 2 continuously iterates the technology, builds the underlying technical framework Lego for developers, and reduces development costs.</p>
<h2 id="about-mixin-network" tabindex="-1"><a class="header-anchor" href="#about-mixin-network" aria-hidden="true">#</a> About Mixin Network</h2>
<p>Mixin Network is an open-source, lightning-fast, and decentralized Web3 platform to bring speed and scalability to the blockchain. Mixin allows blockchains to gain trillions of TPS, sub-second final confirmation, zero transaction fee, enhanced privacy, and unlimited extensibility.</p>
<p>Mixin Network is a PoS network with 26 full nodes. As a layer-2 solution, it has supported 41 public blockchains including Bitcoin, Ethereum, Monero, Polkadot, etc. The total assets on the network have been over 2 billion US Dollars. Mixin is also a full-featured financial platform with functions of AMM, aggregating trade, pending orders on Exchange platforms, unbiased stable currency, etc. Mixin Network is dedicated to providing users with a decentralized blockchain infrastructure that always puts security, privacy, and decentralization first.</p>
<h2 id="follow-us" tabindex="-1"><a class="header-anchor" href="#follow-us" aria-hidden="true">#</a> Follow us:</h2>
<p>Official Website:<a href="https://mixin.one/" target="_blank" rel="noopener noreferrer">https://mixin.one<ExternalLinkIcon/></a></p>
<p>Twitter: <a href="https://twitter.com/Mixin_Network/" target="_blank" rel="noopener noreferrer">https://twitter.com/Mixin_Network<ExternalLinkIcon/></a></p>
<p>Facebook: <a href="https://www.facebook.com/MixinNetwork" target="_blank" rel="noopener noreferrer">https://www.facebook.com/MixinNetwork<ExternalLinkIcon/></a></p>
</div></template>
