<template><div><h1 id="mixin-network-established-strategic-partnership-with-saito" tabindex="-1"><a class="header-anchor" href="#mixin-network-established-strategic-partnership-with-saito" aria-hidden="true">#</a> Mixin Network Established Strategic Partnership With Saito</h1>
<p><img src="@source/blog/2021/mixin-network-established-strategic-partnership-with-saito/saito-mixin.png" alt="saito-mixin"></p>
<p>Mixin Network is excited to announce a strategic partnership with Saito. Saito is an open network that runs cryptocurrency applications in browsers without plugins, private APIs and non-open infrastructure. Saito is dedicated to delivering the Web3 Foundation and the Future of the Decentralized Internet.</p>
<p>The collaboration will begin with integration of SAITO into the industry leading Mixin Messenger, and expand to deeper strategic cooperation. Mixin will integrate Saito into its multi-chain network ecosystem and also bring its extensive community into the Saito ecosystem.</p>
<p>Mixin Network and Saito will work closely to explore opportunities to integrate their networks in ways that benefit users, and protect openness while reducing cost. This will include access to multiple decentralized applications on Mixin Network, SAITO holders will have the chance to use SAITO in practical application scenarios.</p>
<p>Both Saito and Mixin Network care deeply about their communities and users are always welcome to join in, meet cryptocurrency friends, get the latest news about Saito, and get benefits from the secure and scalable blockchain infrastructure.</p>
<h2 id="about-saito" tabindex="-1"><a class="header-anchor" href="#about-saito" aria-hidden="true">#</a> About Saito</h2>
<p>Saito is an open network layer that delivers web3 to users. Applications on Saito can run without closed plugins, private APIs and non-open infrastructure. Saito runs without an owner while funding the nodes that provide routing and user infrastructure for its own network and other public blockchains. All this is powered by an entirely new blockchain design — Saito consensus.</p>
<h2 id="about-mixin-network" tabindex="-1"><a class="header-anchor" href="#about-mixin-network" aria-hidden="true">#</a> About Mixin Network</h2>
<p>Mixin Network is an open-source, lightning-fast, and decentralized Web3 platform to bring speed and scalability to the blockchain. Mixin allows blockchains to gain trillions of TPS, sub-second final confirmation, zero transaction fee, enhanced privacy, and unlimited extensibility.</p>
<p>Mixin Network is a PoS network with 26 full nodes. As a layer-2 solution, it has supported 41 public blockchains including Bitcoin, Ethereum, Monero, Polkadot, etc. The total assets on the network have been over 2 billion US Dollars. Mixin is also a full-featured financial platform with functions of AMM, aggregating trade, pending orders on Exchange platforms, unbiased stable currency, etc. Mixin Network is dedicated to providing users with a decentralized blockchain infrastructure that always puts security, privacy, and decentralization first.</p>
<h2 id="follow-us" tabindex="-1"><a class="header-anchor" href="#follow-us" aria-hidden="true">#</a> Follow us:</h2>
<p>Official Website:<a href="https://mixin.one/" target="_blank" rel="noopener noreferrer">https://mixin.one<ExternalLinkIcon/></a></p>
<p>Twitter: <a href="https://twitter.com/Mixin_Network/" target="_blank" rel="noopener noreferrer">https://twitter.com/Mixin_Network<ExternalLinkIcon/></a></p>
<p>Facebook: <a href="https://www.facebook.com/MixinNetwork" target="_blank" rel="noopener noreferrer">https://www.facebook.com/MixinNetwork<ExternalLinkIcon/></a></p>
</div></template>
