<template><div><h1 id="mixin-meet-up-caw-coffee-and-women-live-painting" tabindex="-1"><a class="header-anchor" href="#mixin-meet-up-caw-coffee-and-women-live-painting" aria-hidden="true">#</a> Mixin Meet-up: CAW (Coffee and Women) Live Painting</h1>
<p><img src="@source/news/mixin-meet-up-caw-coffee-and-women-live-painting/live-painting.png" alt="live-painting"></p>
<p>September 11, 2022: offline meet-up CAW (Coffee and Women) Live Painting event was sucessfully held by Mixin Network at The 5-star Movenpick Hotel Dubai.</p>
<p>During the event, there were more than 15 artists performing live painting with amazing works. CAW is planning to launch their NFTs on Opensea and Trident on Mixin Network. Meng Chan Shu from Mixin Network shared with the participants about his expertise about blockchain, crypto and Mixin Network to the artists, which was highly welcomed.</p>
<h2 id="about-mixin-network" tabindex="-1"><a class="header-anchor" href="#about-mixin-network" aria-hidden="true">#</a> About Mixin Network</h2>
<p>Mixin Network is an open-source, lightning-fast, and decentralized W3 platform to bring speed and scalability to the blockchain. Mixin allows blockchains to gain trillions of TPS, sub-second final confirmation, zero transaction fee, enhanced privacy and unlimited extensibility.
Mixin Network is a PoS network with 26 full nodes. As a wallet solution, it is currently supporting 41 public blockchains including Bitcoin, Ethereum, Avalanche, Polkadot, etc. The total assets on the network have been over 1 billion US Dollars. Mixin is also a full-featured financial platform with functions of AMM, aggregating trade, pending orders on Exchange platforms, unbiased stable currency, etc. Mixin Network is dedicated to providing users with a decentralized blockchain infrastructure that always puts security, privacy, and decentralization first.</p>
<p>Follow us:
<a href="https://mixin.one/" target="_blank" rel="noopener noreferrer">Official Website<ExternalLinkIcon/></a>｜<a href="https://twitter.com/Mixin_Network" target="_blank" rel="noopener noreferrer">Twitter<ExternalLinkIcon/></a>｜<a href="https://www.facebook.com/MixinNetwork" target="_blank" rel="noopener noreferrer">Facebook<ExternalLinkIcon/></a>｜<a href="https://medium.com/mixinnetwork" target="_blank" rel="noopener noreferrer">Medium<ExternalLinkIcon/></a>｜<a href="http://contact@mixin.one" target="_blank" rel="noopener noreferrer">Email<ExternalLinkIcon/></a> ｜<a href="https://instagram.com/mixinnetwork" target="_blank" rel="noopener noreferrer">Instagram<ExternalLinkIcon/></a></p>
<h2 id="about-trident" tabindex="-1"><a class="header-anchor" href="#about-trident" aria-hidden="true">#</a> About Trident</h2>
<p>Trident is an easy-to-use NFT marketplace for every general user, built on Mixin Network, powered by <a href="https://github.com/MixinNetwork/trusted-group" target="_blank" rel="noopener noreferrer">MTG<ExternalLinkIcon/></a> technology.
• Fast and gas free. In Mixin Network, transfer is extremely fast and no gas will be charged.
• Safe. Assets are safely protected by MTG technology.
• Easy to use. Use it like a normal shopping application.</p>
<p>|<a href="https://thetrident.one/" target="_blank" rel="noopener noreferrer">Official website<ExternalLinkIcon/></a>| <a href="https://twitter.com/trident_nft" target="_blank" rel="noopener noreferrer">Twitter<ExternalLinkIcon/></a>|</p>
</div></template>
