<template><div><h1 id="mixin-network-joins-near-ecosystem" tabindex="-1"><a class="header-anchor" href="#mixin-network-joins-near-ecosystem" aria-hidden="true">#</a> Mixin Network Joins NEAR Ecosystem</h1>
<p><img src="@source/blog/2021/mixin-network-joins-near-ecosystem/near-mixin.png" alt="near-mixin"></p>
<p>Mixin Network is pleased to announce that it has joined NEAR’s ecosystem as a scalable layer 2 solution. NEAR Protocol is a network for a world reimagined. Through simple, secure, and scalable technology, millions are empowered to invent and explore new experiences. Business, creativity, and community are being reimagined for a more sustainable and inclusive future.</p>
<p>The collaboration will begin with integration of NEAR into the industry-leading Mixin Messenger, and expand to deeper strategic cooperation in market promotion and global community expansion, etc. Mixin now has supported NEAR in its multi-chain network ecosystem and will bring its extensive community into the NEAR ecosystem.</p>
<p>Mixin Network and NEAR will work closely to explore opportunities to integrate their networks in ways that benefit users. This will include access to multiple decentralized applications on Mixin Network, NEAR holders will have the chance to use NEAR in more practical application scenarios.</p>
<p>Both NEAR and Mixin Network care deeply about their communities. Users are always welcome to join in, meet cryptocurrency friends, get the latest news about NEAR, and get benefits from the secure and scalable blockchain infrastructure!</p>
<h2 id="about-near-protocol" tabindex="-1"><a class="header-anchor" href="#about-near-protocol" aria-hidden="true">#</a> About NEAR Protocol</h2>
<p><a href="https://near.org/%22near%22" target="_blank" rel="noopener noreferrer">NEAR Protocol<ExternalLinkIcon/></a> is a high-performance blockchain that is designed to be super-fast, incredibly secure, and infinitely scalable. NEAR’s vision is to create a network that enables people to re-imagine finance, creativity and community in new and inclusive ways.</p>
<h2 id="about-mixin-network" tabindex="-1"><a class="header-anchor" href="#about-mixin-network" aria-hidden="true">#</a> About Mixin Network</h2>
<p>Mixin Network is an open-source, lightning-fast, and decentralized Web3 platform to bring speed and scalability to the blockchain. Mixin allows blockchains to gain trillions of TPS, sub-second final confirmation, zero transaction fee, enhanced privacy, and unlimited extensibility.</p>
<p>Mixin Network is a PoS network with 26 full nodes. As a layer-2 solution, it has supported 41 public blockchains including Bitcoin, Ethereum, Monero, Polkadot, etc. The total assets on the network have been over 2 billion US Dollars. Mixin is also a full-featured financial platform with functions of AMM, aggregating trade, pending orders on Exchange platforms, unbiased stable currency, etc. Mixin Network is dedicated to providing users with a decentralized blockchain infrastructure that always puts security, privacy, and decentralization first.</p>
<h2 id="follow-us" tabindex="-1"><a class="header-anchor" href="#follow-us" aria-hidden="true">#</a> Follow us:</h2>
<p>Official Website:<a href="https://mixin.one/" target="_blank" rel="noopener noreferrer">https://mixin.one<ExternalLinkIcon/></a></p>
<p>Twitter: <a href="https://twitter.com/Mixin_Network/" target="_blank" rel="noopener noreferrer">https://twitter.com/Mixin_Network<ExternalLinkIcon/></a></p>
<p>Facebook: <a href="https://www.facebook.com/MixinNetwork" target="_blank" rel="noopener noreferrer">https://www.facebook.com/MixinNetwork<ExternalLinkIcon/></a></p>
</div></template>
