<template><div><h1 id="mixin-network-establishes-strategic-partnership-with-subquery" tabindex="-1"><a class="header-anchor" href="#mixin-network-establishes-strategic-partnership-with-subquery" aria-hidden="true">#</a> Mixin Network Establishes Strategic Partnership With SubQuery</h1>
<p><img src="@source/blog/2021/mixin-network-establishes-strategic-partnership-with-subquery/subquery-mixin.png" alt="subquery-mixin"></p>
<p>Mixin Network is glad to announce a strategic partnership with SubQuery. SubQuery is a decentralized data aggregation, indexing &amp; querying layer between Layer-1 blockchains and decentralized applications (DApps). Currently focused on Polkadot and Substrate projects, this data-as-a-service allows developers to focus on their core use case and front-end, without needing to waste time on building a custom backend for data processing.</p>
<p>Together, both parties will work together to grow and engage SubQuery’s community in China through Mixin Messenger. Through this partnership, Mixin Network will work closely with SubQuery in market promotion, network construction, and global community expansion. This will include bringing more developers to the SubQuery network and also give common users a chance to access and use the multiple decentralized applications on the Mixin Network.</p>
<p>SubQuery is working with Mixin Messenger to provide core data on assets and transactions in the growing Polkadot/Kusama ecosystem. Through the common API model that SubQuery has designed, Mixin will easily be able to onboard new parachain tokens.</p>
<p>Both SubQuery and Mixin Network care deeply about their communities. All users, regardless of where they are located, are invited to join a growing community and get the latest news about SubQuery. Click <a href="https://subquery.mixinbots.com/join" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a>to join today!</p>
<h2 id="about-subquery" tabindex="-1"><a class="header-anchor" href="#about-subquery" aria-hidden="true">#</a> About SubQuery</h2>
<p>SubQuery is a data aggregation layer that will operate between blockchains (like Polkadot) and DApps (like Mixin Messenger). This service allows DApp developers to focus on their core use case and front-end, without needing to waste time on building a custom backend for data processing.</p>
<p><a href="https://subquery.network/" target="_blank" rel="noopener noreferrer">Website<ExternalLinkIcon/></a> | <a href="http://hello@subquery.network/" target="_blank" rel="noopener noreferrer">Email<ExternalLinkIcon/></a> | <a href="https://discord.com/invite/78zg8aBSMG" target="_blank" rel="noopener noreferrer">Discord<ExternalLinkIcon/></a> | <a href="https://t.me/subquerynetwork" target="_blank" rel="noopener noreferrer">Telegram<ExternalLinkIcon/></a> | <a href="https://twitter.com/subquerynetwork" target="_blank" rel="noopener noreferrer">Twitter<ExternalLinkIcon/></a> | <a href="https://matrix.to/#/#subquery:matrix.org" target="_blank" rel="noopener noreferrer">Matrix<ExternalLinkIcon/></a> | <a href="https://www.linkedin.com/company/subquery" target="_blank" rel="noopener noreferrer">LinkedIn<ExternalLinkIcon/></a></p>
<h2 id="about-mixin-network" tabindex="-1"><a class="header-anchor" href="#about-mixin-network" aria-hidden="true">#</a> About Mixin Network</h2>
<p>Mixin Network is an open-source, lightning-fast, and decentralized Web3 platform to bring speed and scalability to the blockchain. Mixin allows blockchains to gain trillions of TPS, sub-second final confirmation, zero transaction fee, enhanced privacy, and unlimited extensibility.</p>
<p>Mixin Network is a PoS network with 26 full nodes. As a layer-2 solution, it has supported 41 public blockchains including Bitcoin, Ethereum, Monero, Polkadot, etc. The total assets on the network have been over 2 billion US Dollars. Mixin is also a full-featured financial platform with functions of AMM, aggregating trade, pending orders on Exchange platforms, unbiased stable currency, etc. Mixin Network is dedicated to providing users with a decentralized blockchain infrastructure that always puts security, privacy, and decentralization first.</p>
<h2 id="follow-us" tabindex="-1"><a class="header-anchor" href="#follow-us" aria-hidden="true">#</a> Follow us:</h2>
<p>Official Website:<a href="https://mixin.one/" target="_blank" rel="noopener noreferrer">https://mixin.one<ExternalLinkIcon/></a></p>
<p>Twitter: <a href="https://twitter.com/Mixin_Network/" target="_blank" rel="noopener noreferrer">https://twitter.com/Mixin_Network<ExternalLinkIcon/></a></p>
<p>Facebook: <a href="https://www.facebook.com/MixinNetwork" target="_blank" rel="noopener noreferrer">https://www.facebook.com/MixinNetwork<ExternalLinkIcon/></a></p>
</div></template>
