<template><div><h1 id="bake-n-more-the-first-cafe-in-dubai-to-accept-crypto-payment-powered-by-mixin" tabindex="-1"><a class="header-anchor" href="#bake-n-more-the-first-cafe-in-dubai-to-accept-crypto-payment-powered-by-mixin" aria-hidden="true">#</a> Bake N More, the First Cafe in Dubai to Accept Crypto Payment-Powered by Mixin</h1>
<p><img src="@source/blog/2022/bake-n-more-the-first-cafe-in-dubai-to-accept-crypto-payment-powered-by-mixin/partnership.png" alt="partnership"></p>
<p><a href="https://www.instagram.com/bakenmore.ae/%22bakenmore%22" target="_blank" rel="noopener noreferrer">Bake N More<ExternalLinkIcon/></a>, a Dubai-based Café, is the most recent business in the city to accept digital currency as payment. At Bake N More, customers can pay for and enjoy their fresh baked goods with cryptocurrency without incurring any transaction fee. Bake N More will be serving freshly prepared all-day breakfast, brewed coffee, breads, baked goods, salads, and unique sandwiches. Bake N More’s factory is equipped with an advanced, cutting-edge semi-automated assembly-line production that is operational round the clock and possesses the capacity to produce high volumes of products for the café’s partners.</p>
<p>Talking about the thought process behind this charming new café and excited about its launch, Mohammad Al Hammadi, Owner of Bake N More said, “Our society needs the transition from eating unhealthy food filled by preservatives, artificial flavors, and emulsifiers, hence we decided to make the food space better by sharing our fresh and healthy products with our community. We lovingly bake a wide variety of breads, pastries, all kinds of slices, muffins, macarons, brownies, and more, while insisting on the finest ingredients and quality of the products. Our French award winner- executive chef, David Croiser, brings over 25 years’ experience, he believes tasty foods don’t need to be unhealthy, thus we have invested in the best ingredients and skilled human resources who are synergistically moving together to ensure that we deliver the highest quality product with the best customer service. We are delighted and privileged to welcome business partners and customers to our coffee shop and serve them with our fresh and hot out of the oven nourishments.”</p>
<p>The contemporary café’s open-source payment platform is handled by Mixin Network which allows customers to pay for their purchases with Bitcoin, Ethereum, Tether and 3 other major cryptocurrencies. All existing payment methods like cash, cards and online payments are accepted. Mixin Network is a lightning fast, decentralized Web3 platform that brings speed and scalability to blockchain and allows blockchains to gain trillions of TPS, sub-second final confirmation, zero transaction fee, enhanced privacy, and unlimited extensibility.</p>
<p>Delighted about their collaboration with Bake N More, Meng Chan Shu, Global Ambassador of Mixin Network said, “Mixin Messenger is not just a normal chatting app, it is also a decentralized crypto wallet that is connected to 41 public chains with more than 2 billion USD under asset. It is also lightning fast in transferring tokens and has never been successfully hacked in the last 4 years. With no gas fee among users, it is a solution that can help Bake N More unlock the copious advantages of a payment system that is safe, speedy, and simple.”</p>
<p>Bake N More’s POS and ERP are powered by an all-in-one Dubai-based solution, IIKO, who brings advanced technologies to F&amp;B outlets with an intelligent cloud-based system. IIKO is currently operating in 51 countries, covering multiple restaurant functionalities and brings superior operational practices into the life of a restaurant to help maximize their profits and minimize their hassle.</p>
<p>Optimistic about their partnership with Bake N More, Alex Ponomarev from IIKO said, “We are happy to collaborate with a trendsetting café like Bake N More and we are looking forward to helping them operate in the most business efficient manner. Along with the outstanding operational practices that we have introduced to the hospitality businesses, we will act as a technology center for the whole restaurant operation aggregating all the third-party solutions, including payments through Mixin Network, enhancing the overall functionality and providing more capabilities to the business”.</p>
<p>Bake N More is here to cater to a clientele that loves healthy and fresh food that tastes good. Through their café, they want to build and maintain a business strategy that is prosperous and fruitful through the medium of providing quality upscale baked products for a variety of consumers. They are committed to providing superior quality to meet their customers’ needs through progressive processes that help achieve sustained excellence.</p>
<h2 id="about-bake-n-more" tabindex="-1"><a class="header-anchor" href="#about-bake-n-more" aria-hidden="true">#</a> About Bake N More</h2>
<p>Bake N More factory is equipped with an advanced, leading edge semi-automated assembly-line production that is operational 24 hours per day with the capacity to produce high volumes of products for our B2B partners. Also, we are privileged to welcome customers to our coffee shop and serve them with our fresh and hot out of the oven nourishments.</p>
<p>Our mission in Bake N More Factory is to create long-term partnerships with customers by ensuring to deliver the highest quality product with the best customer service. We are here to build and maintain a business strategy that is prosperous and fruitful involving a steady growth and innovation by providing a quality upscale baked product for various consumers. We are committed to provide valued quality to meet our customers’ needs and to achieve excellence by following the safe and legal food products produced in compliance with all regulatory standards. To ensure best practice we have established the internationally recognized Hazard Analysis Critical Control Point (HACCP) system and applying the latest technology and innovation and our highly trained committed team ensure that all goods are produced in a way to meet our customers’ requirement. Bake N More Factory provides services to businesses and individuals</p>
<p>Follow us: <a href="https://bakenmore.ae/" target="_blank" rel="noopener noreferrer">Official Website<ExternalLinkIcon/></a>｜<a href="https://www.instagram.com/bakenmorecafe/?hl=en" target="_blank" rel="noopener noreferrer">Instagram<ExternalLinkIcon/></a>｜<a href="https://www.facebook.com/bakenmoreAE" target="_blank" rel="noopener noreferrer">Facebook<ExternalLinkIcon/></a></p>
<h2 id="about-mixin-network" tabindex="-1"><a class="header-anchor" href="#about-mixin-network" aria-hidden="true">#</a> About Mixin Network</h2>
<p>Mixin Network is an open-source, lightning-fast, and decentralized W3 platform to bring speed and scalability to the blockchain. Mixin allows blockchains to gain trillions of TPS, sub-second final confirmation, zero transaction fee, enhanced privacy and unlimited extensibility.</p>
<p>Mixin Network is a PoS network with 38 full nodes. As a layer-2 solution, it has supported 41 public blockchains including Bitcoin, Ethereum, Monero, Polkadot, etc. The total assets on the network have been over 2 billion US Dollars. Mixin is also a full-featured financial platform with functions of AMM, aggregating trade, pending orders on Exchange platforms, unbiased stable currency, etc. Mixin Network is dedicated to providing users with a decentralized blockchain infrastructure that always puts security, privacy, and decentralization first.</p>
<p>Follow us: <a href="https://mixin.one/" target="_blank" rel="noopener noreferrer">Official Website<ExternalLinkIcon/></a>｜<a href="https://twitter.com/Mixin_Network/" target="_blank" rel="noopener noreferrer">Twitter<ExternalLinkIcon/></a>｜<a href="https://www.facebook.com/MixinNetwork" target="_blank" rel="noopener noreferrer">Facebook<ExternalLinkIcon/></a>｜<a href="https://medium.com/mixinnetwork" target="_blank" rel="noopener noreferrer">Medium<ExternalLinkIcon/></a>｜<a href="contact@mixin.one">Email</a></p>
<h2 id="about-iiko-east-dmcc" tabindex="-1"><a class="header-anchor" href="#about-iiko-east-dmcc" aria-hidden="true">#</a> About IIKO East DMCC</h2>
<p>iiko is a global restaurant POS &amp; ERP provider opeating in 51 countries. Having started in 2005 iiko has been chosen by more than 70 000 venues and is operated daily in more than 45000 places across the globe. Covering all of the functionalities in the restaurant iiko brings the best operational practices into the life of a restaurant willing to raise profits and reduce hassle. iikoMiddleEast is iiko’s branch covering the MENA region operating from Dubai. Over the last 3 years the company has gained more than 1000 venues in several countries.</p>
<p>Follow us: <a href="https://iiko.ae/" target="_blank" rel="noopener noreferrer">Official Website<ExternalLinkIcon/></a>｜<a href="https://www.instagram.com/iikomiddleeast/" target="_blank" rel="noopener noreferrer">Instagram<ExternalLinkIcon/></a>｜<a href="https://www.facebook.com/iikomiddleeast/" target="_blank" rel="noopener noreferrer">Facebook<ExternalLinkIcon/></a></p>
</div></template>
