<template><div><h1 id="mixin-joins-avalanche-validator-ecosystem-to-provide-staking-services-to-users" tabindex="-1"><a class="header-anchor" href="#mixin-joins-avalanche-validator-ecosystem-to-provide-staking-services-to-users" aria-hidden="true">#</a> Mixin Joins Avalanche Validator Ecosystem to Provide Staking Services to Users</h1>
<p><img src="@source/blog/2021/mixin-joins-avalanche-validator-ecosystem-to-provide-staking-services-to-users/avalanche-mixin.png" alt="avalanche-mixin"></p>
<p>Avalanche Protocol is an open-source blockchain platform designed for DeFi with high throughput, low latency, fast finality, and scalability. Smart contracts can be confirmed in less than 1 second and support a full set of Ethereum development toolkits while supporting millions of independent verifiers to participate as miners.</p>
<p>Mixin Network has integrated with Avalanche and started a strategic partnership with them. Exin, as one of the most active developer teams in the Mixin ecosystem, owns the popular staking product ExinPool, which will join the Avalanche validator node ecosystem to provide secure and trusted staking and node services to the community.</p>
<p>ExinPool nodes have a queuing mechanism for joining and exiting (ignoring the rule that the 14-day locked period for staking), providing excellent liquidity and allowing users to participate in staking with zero thresholds and earn stable returns.</p>
<p>ExinPool encourages the community to participate in node co-construction and profit from the early-bird benefits in the early stages of the Avalanche node. Currently, the AVAX Staking Annualized Percentage Rate (APR) is about 10.08%. Users participating through ExinPool can enjoy super-high node revenue dividends while receiving additional AVAX, BTC, and EPC rewards during the campaign period. Significantly increasing the rate of return (short-term APR is close to 15%, exclusive of the extra BTC, EPC rewards). The details of the early-bird benefits are as follows:</p>
<ul>
<li>99% of node staking rewards will be returned to each node    participant daily.</li>
<li>Users who participate in staking every 10 AVAX can enjoy a reward of 0.001 AVAX per day for 3 months (the maximum reward is for the top 10000 AVAX participants, that is, the maximum reward is 1 AVAX per day).</li>
<li>There will be a BTC bonus distribution to participants, with a daily BTC bonus of 100 Satoshi for every 10 AVAX from the participant lasting for one month.</li>
<li>In addition, those who participate in ExinPool AVAX nodes will receive EPC bonus: every 10 AVAX staked, participants can earn 10 EPC per day lasting for one month.</li>
<li>Follow-up activities that may be launched: ExinPool users who stake AVAX with ExinPool could receive LP Token, which can be used for trading, mortgage, lending, etc.</li>
<li>Note: The returns and bonuses are distributed through ExinPool, with zero transaction fee.</li>
</ul>
<p>ExinPool is committed to build the Avalanche ecosystem and jointly promote network stability and decentralization. Users can participate in the Avalanche ExinPool node through the entrance on Mixin Messenger to get stable returns easily. Meanwhile, welcome to join the official Avalanche community and learn more. Click <a href="https://avalanche.mixinbots.com/join" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a> to join now!</p>
<h2 id="about-avalanche" tabindex="-1"><a class="header-anchor" href="#about-avalanche" aria-hidden="true">#</a> About Avalanche</h2>
<p>Avalanche is the fastest smart contracts platform in the blockchain industry, as measured by time-to-finality, and has the most validators securing its activity of any proof-of-stake protocol. Avalanche is blazingly fast, low cost, and green. Any smart contract-enabled application can outperform its competition on Avalanche.</p>
<h2 id="about-mixin-network" tabindex="-1"><a class="header-anchor" href="#about-mixin-network" aria-hidden="true">#</a> About Mixin Network</h2>
<p>Mixin Network is an open-source, lightning-fast, and decentralized Web3 platform to bring speed and scalability to the blockchain. Mixin allows blockchains to gain trillions of TPS, sub-second final confirmation, zero transaction fee, enhanced privacy, and unlimited extensibility.</p>
<p>Mixin Network is a PoS network with 26 full nodes. As a layer-2 solution, it has supported 41 public blockchains including Bitcoin, Ethereum, Monero, Polkadot, etc. The total assets on the network have been over 2 billion US Dollars. Mixin is also a full-featured financial platform with functions of AMM, aggregating trade, pending orders on Exchange platforms, unbiased stable currency, etc. Mixin Network is dedicated to providing users with a decentralized blockchain infrastructure that always puts security, privacy, and decentralization first.</p>
<h2 id="follow-us" tabindex="-1"><a class="header-anchor" href="#follow-us" aria-hidden="true">#</a> Follow us:</h2>
<p>Official Website:<a href="https://mixin.one/" target="_blank" rel="noopener noreferrer">https://mixin.one<ExternalLinkIcon/></a></p>
<p>Twitter: <a href="https://twitter.com/Mixin_Network/" target="_blank" rel="noopener noreferrer">https://twitter.com/Mixin_Network<ExternalLinkIcon/></a></p>
<p>Facebook: <a href="https://www.facebook.com/MixinNetwork" target="_blank" rel="noopener noreferrer">https://www.facebook.com/MixinNetwork<ExternalLinkIcon/></a></p>
</div></template>
